# Generated by Django 5.2.16 on 2026-08-13 07:43

from django.db import migrations, models

import cvat.apps.iam.models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_move_user_content_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", cvat.apps.iam.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("email_password", "EMAIL_PASSWORD"),
                    ("social", "SOCIAL"),
                    ("sso", "SSO"),
                    ("ldap", "LDAP"),
                    ("invitation", "INVITATION"),
                    ("admin", "ADMIN"),
                    ("system", "SYSTEM"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
